
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-11
owner: ucsb-cs156-f25
repo_name: team02-f25-11
pull_requests: [{"author":{"id":"U_kgDOCNoLqQ","is_bot":false,"login":"SagnikBiswasUCSB","name":""},"headRefName":"recommendationrequest-editindexpage","number":126,"title":"refactored index page for recommendation request","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/126"},{"author":{"id":"U_kgDOCNnsTg","is_bot":false,"login":"EthanChung137","name":""},"headRefName":"EthanChung137-UCSBDiningCommonsMenuItem-Integration-Test","number":125,"title":"Adding integration test for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/125"},{"author":{"id":"U_kgDOBigf6g","is_bot":false,"login":"wooblz","name":""},"headRefName":"wooblz-articlesE2ETest","number":124,"title":"Wooblz articles e2e test","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/124"},{"author":{"id":"U_kgDOBigf6g","is_bot":false,"login":"wooblz","name":""},"headRefName":"wooblz-patch-1","number":120,"title":"Update README.md with links +title","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/120"}]
