
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-11
owner: ucsb-cs156-f25
repo_name: team02-f25-11
pull_requests: [{"author":{"id":"U_kgDOCNnsTg","is_bot":false,"login":"EthanChung137","name":""},"headRefName":"EthanChung137-UCSBDiningCommonsMenuItem-edit-page","number":104,"title":"EthanChung137 Added EditPage for UCSBDiningCommonsMenuItem and Relevant Tests/Storybook","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/104"},{"author":{"id":"U_kgDOCNnsTg","is_bot":false,"login":"EthanChung137","name":""},"headRefName":"EthanChung137-UCSBDiningCommonsMenuItem-index-page","number":102,"title":"EthanChung137 UCSBDiningCommonsMenuItem Index Page","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/102"},{"author":{"id":"U_kgDOCCbFVA","is_bot":false,"login":"tara-rezaei","name":""},"headRefName":"tara-MenuItemReview-FormComponentV2","number":98,"title":"Form Component for MenuItemReview plus testsTara menu item review form component v2","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/98"},{"author":{"id":"U_kgDOCCbFVA","is_bot":false,"login":"tara-rezaei","name":""},"headRefName":"tara-MenuItemReview-fixtures","number":76,"title":"Created fixtures for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/76"},{"author":{"id":"U_kgDOCCbFVA","is_bot":false,"login":"tara-rezaei","name":""},"headRefName":"tara-MenuItemReview-backend","number":66,"title":"Copy files for Backend CRUD API MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-11/pull/66"}]
